In [2]:
import pandas as pd
import os
import requests
from bs4 import BeautifulSoup

In [3]:
import requests

headers = {
    'sec-ch-ua-platform': '"Windows"',
    'Referer': 'https://www.fotmob.com/en-GB/teams/8549/stats/middlesbrough/players',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36',
    'x-mas': 'eyJib2R5Ijp7InVybCI6Ii9hcGkvZGF0YS90ZWFtc2Vhc29uc3RhdHM/dGVhbUlkPTg1NDkmdG91cm5hbWVudElkPTI3MTk1JmlzVGVhbVN1YlRhYj1mYWxzZSIsImNvZGUiOjE3ODQ4OTA0MDExODUsImZvbyI6InByb2R1Y3Rpb246NWQ1Mjc3YzgwN2Y1NzUzOTc4YTJiMDZjYjgzZTVmYWM5M2QxM2ZjYiJ9LCJzaWduYXR1cmUiOiI5OTdGQkVCMjY5QjFDMDEwOUY4MkUzMEZGQUVFODY2NSJ9',
    'sec-ch-ua': '"Not;A=Brand";v="8", "Chromium";v="150", "Google Chrome";v="150"',
    'sec-ch-ua-mobile': '?0',
}

params = {
    'teamId': '8549',
    'tournamentId': '27195',
    'isTeamSubTab': 'false',
}

response = requests.get('https://www.fotmob.com/api/data/teamseasonstats', params=params, headers=headers)

In [4]:
data = response.json()

In [5]:
player_data = data['players']
top_scorers = player_data[0]['topThree']
names = []
ranks = []
countries = []
values = []
stat_names = []

for i in range(len(player_data)):
    top_three = player_data[i]['topThree']
    for j in range(len(top_three)):
        names.append(top_three[j]['name'])
        ranks.append(top_three[j]['rank'])
        countries.append(top_three[j]['ccode'])
        values.append(top_three[j]['value'])
        stat_names.append(player_data[i]['header'])

player_df = pd.DataFrame({'Name': names,
             'League Rank': ranks,
             'Country': countries,
             'Value': values,
             'Stat Name': stat_names})

In [6]:
player_df['Stat Name'].unique()

array(['Top scorer', 'Assists', 'Goals + Assists', 'FotMob rating',
       'Minutes played', 'Goals per 90', 'Expected goals (xG)',
       'Expected goals (xG) per 90', 'Expected goals on target (xGOT)',
       'Shots on target per 90', 'Shots per 90', 'Accurate passes per 90',
       'Big chances created', 'Chances created',
       'Accurate long balls per 90', 'Expected assist (xA)',
       'Expected assist (xA) per 90', 'xG + xA per 90',
       'Successful dribbles per 90', 'Big chances missed',
       'Penalties won', 'Defensive actions per 90', 'Tackles per 90',
       'Interceptions per 90', 'Clearances per 90', 'Blocks per 90',
       'Recoveries per 90', 'Penalties conceded',
       'Possession won final 3rd per 90', 'Clean sheets',
       'Save percentage', 'Saves per 90', 'Goals prevented',
       'Goals conceded per 90', 'Fouls committed per 90', 'Yellow cards',
       'Red cards'], dtype=object)

In [7]:
# player_df.to_excel('boro_player_df.xlsx', index=False)

In [8]:
team_data = data['teams']

names = []
ranks = []
countries = []
values = []
stat_names = []

for i in range(len(team_data)):
    top_three = team_data[i]['topThree']
    for j in range(len(top_three)):
        names.append(top_three[j]['name'])
        ranks.append(top_three[j]['rank'])
        countries.append(top_three[j]['ccode'])
        values.append(top_three[j]['value'])
        stat_names.append(team_data[i]['header'])

team_df = pd.DataFrame({'Team': names,
             'League Rank': ranks,
             'Country': countries,
             'Value': values,
             'Stat Name': stat_names})

In [9]:
team_df['Stat Name'].unique()

array(['FotMob rating', 'Goals per match', 'Goals conceded per match',
       'Average possession', 'Clean sheets', 'Attendance',
       'Expected goals', 'xG difference', 'Shots on target per match',
       'Big chances', 'Big chances missed', 'Accurate passes per match',
       'Accurate long balls per match', 'Accurate crosses per match',
       'Penalties awarded', 'Touches in opposition box', 'Corners',
       'Set piece goals', 'xG conceded', 'Interceptions per match',
       'Tackles per match', 'Clearances per match',
       'Possession won final 3rd per match', 'Set piece goals conceded',
       'Penalties conceded', 'Saves per match', 'Fouls per match',
       'Yellow cards', 'Red cards'], dtype=object)

In [10]:
team_df.loc[team_df['Team'] == 'Middlesbrough'].sort_values('League Rank')

,Team,League Rank,Country,Value,Stat Name
9,Middlesbrough,1,ENG,59.50,Average possession
72,Middlesbrough,1,ENG,8.00,Penalties conceded
33,Middlesbrough,1,ENG,436.80,Accurate passes per match
54,Middlesbrough,1,ENG,44.10,xG conceded
48,Middlesbrough,1,ENG,314.00,Corners
45,Middlesbrough,1,ENG,1455.00,Touches in opposition box
1,Middlesbrough,2,ENG,7.02,FotMob rating
7,Middlesbrough,2,ENG,1.00,Goals conceded per match
23,Middlesbrough,3,ENG,28.00,xG difference
5,Middlesbrough,4,ENG,1.60,Goals per match
26,Middlesbrough,4,ENG,5.00,Shots on target per match
68,Middlesbrough,4,ENG,3.90,Possession won final 3rd per match
20,Middlesbrough,5,ENG,72.10,Expected goals
14,Middlesbrough,6,ENG,13.00,Clean sheets
29,Middlesbrough,6,ENG,107.00,Big chances
17,Middlesbrough,7,ENG,27622.00,Attendance
44,Middlesbrough,8,ENG,4.00,Penalties awarded
62,Middlesbrough,9,ENG,15.70,Tackles per match
41,Middlesbrough,11,ENG,4.40,Accurate crosses per match
32,Middlesbrough,11,ENG,62.00,Big chances missed
71,Middlesbrough,13,ENG,16.00,Set piece goals conceded
53,Middlesbrough,16,ENG,14.00,Set piece goals
38,Middlesbrough,18,ENG,21.10,Accurate long balls per match
83,Middlesbrough,20,ENG,74.00,Yellow cards
86,Middlesbrough,22,ENG,1.00,Red cards
59,Middlesbrough,23,ENG,7.30,Interceptions per match
77,Middlesbrough,23,ENG,2.30,Saves per match
65,Middlesbrough,24,ENG,20.20,Clearances per match
80,Middlesbrough,24,ENG,9.30,Fouls per match

In [11]:
team_df.loc[team_df['Team'] == 'Middlesbrough']

,Team,League Rank,Country,Value,Stat Name
1,Middlesbrough,2,ENG,7.02,FotMob rating
5,Middlesbrough,4,ENG,1.60,Goals per match
7,Middlesbrough,2,ENG,1.00,Goals conceded per match
9,Middlesbrough,1,ENG,59.50,Average possession
14,Middlesbrough,6,ENG,13.00,Clean sheets
17,Middlesbrough,7,ENG,27622.00,Attendance
20,Middlesbrough,5,ENG,72.10,Expected goals
23,Middlesbrough,3,ENG,28.00,xG difference
26,Middlesbrough,4,ENG,5.00,Shots on target per match
29,Middlesbrough,6,ENG,107.00,Big chances
32,Middlesbrough,11,ENG,62.00,Big chances missed
33,Middlesbrough,1,ENG,436.80,Accurate passes per match
38,Middlesbrough,18,ENG,21.10,Accurate long balls per match
41,Middlesbrough,11,ENG,4.40,Accurate crosses per match
44,Middlesbrough,8,ENG,4.00,Penalties awarded
45,Middlesbrough,1,ENG,1455.00,Touches in opposition box
48,Middlesbrough,1,ENG,314.00,Corners
53,Middlesbrough,16,ENG,14.00,Set piece goals
54,Middlesbrough,1,ENG,44.10,xG conceded
59,Middlesbrough,23,ENG,7.30,Interceptions per match
62,Middlesbrough,9,ENG,15.70,Tackles per match
65,Middlesbrough,24,ENG,20.20,Clearances per match
68,Middlesbrough,4,ENG,3.90,Possession won final 3rd per match
71,Middlesbrough,13,ENG,16.00,Set piece goals conceded
72,Middlesbrough,1,ENG,8.00,Penalties conceded
77,Middlesbrough,23,ENG,2.30,Saves per match
80,Middlesbrough,24,ENG,9.30,Fouls per match
83,Middlesbrough,20,ENG,74.00,Yellow cards
86,Middlesbrough,22,ENG,1.00,Red cards

In [12]:
# team_df.to_excel('boro_team_df.xlsx', index=False)

In [13]:
xg_conceded_url = 'https://www.fotmob.com/api/data/leagueseasondeepstats?lng=en-GB&id=48&season=27195&type=teams&stat=expected_goals_conceded_team'
xg_faced_response = requests.get(xg_conceded_url, headers=headers)

In [33]:
goals_conceded_url = 'https://www.fotmob.com/api/data/leagueseasondeepstats?lng=en-GB&id=48&season=27195&type=teams&stat=goals_conceded_team_match'
goals_conceded_response = requests.get(goals_conceded_url, headers=headers)

In [21]:
xg_faced_json = xg_faced_response.json()

In [22]:
xg_faced_json.keys()

dict_keys(['statsData', 'seasons', 'statsList', 'leagueDetails', 'type', 'teamName', 'currentSeasonId', 'currentStatName', 'substatTitle', 'substatLocalizedTitleId'])

In [27]:
xg_faced_data = xg_faced_json['statsData']

xg_faced_data[0]

{'id': 8549,
 'teamId': 8549,
 'name': 'Middlesbrough',
 'position': None,
 'substatValue': {'value': 47, 'format': 'number', 'fractions': 0},
 'statValue': {'name': 'expected_goals_conceded_team',
  'value': 44.1,
  'format': 'fraction',
  'fractions': 1},
 'rank': 1,
 'type': 'teams'}

In [34]:
goals_conceded_json = goals_conceded_response.json()

In [35]:
goals_conceded_json.keys()

dict_keys(['statsData', 'seasons', 'statsList', 'leagueDetails', 'type', 'teamName', 'currentSeasonId', 'currentStatName', 'substatTitle', 'substatLocalizedTitleId'])

In [37]:
goals_conceded_data = goals_conceded_json['statsData']

goals_conceded_data[0]

{'id': 8669,
 'teamId': 8669,
 'name': 'Coventry City',
 'position': None,
 'substatValue': {'value': 45, 'format': 'number', 'fractions': 0},
 'statValue': {'name': 'goals_conceded_team_match',
  'value': 1,
  'format': 'fraction',
  'fractions': 1},
 'rank': 1,
 'type': 'teams'}

In [39]:
teams = []
values = []
for i in range(len(goals_conceded_data)):
    teams.append(goals_conceded_data[i]['name'])
    values.append(goals_conceded_data[i]['substatValue']['value'])

goals_conceded_df = pd.DataFrame({'team': teams,
                                  'goals_conceded': values})

goals_conceded_df

                    team  goals_conceded
0          Coventry City              45
1          Middlesbrough              47
2           Ipswich Town              47
3               Millwall              49
4             Stoke City              56
5            Southampton              56
6           Norwich City              56
7       Blackburn Rovers              56
8        Birmingham City              56
9   West Bromwich Albion              58
10     Charlton Athletic              58
11          Swansea City              59
12         Oxford United              59
13          Derby County              59
14          Bristol City              59
15     Preston North End              62
16            Portsmouth              64
17               Wrexham              65
18               Watford              65
19      Sheffield United              66
20             Hull City              66
21        Leicester City              68
22   Queens Park Rangers              73
23   Sheffield Wednesday              89

In [30]:
teams = []
values = []
for i in range (len(xg_faced_data)):
    teams.append(xg_faced_data[i]['name'])
    values.append(xg_faced_data[i]['statValue']['value'])

xg_faced_df = pd.DataFrame({'team': teams,
                            'xg_faced': values})

In [41]:
defence_quality_df = pd.merge(goals_conceded_df, xg_faced_df, how='left', on='team')

defence_quality_df

                    team  goals_conceded  xg_faced
0          Coventry City              45      50.2
1          Middlesbrough              47      44.1
2           Ipswich Town              47      46.6
3               Millwall              49      58.5
4             Stoke City              56      65.1
5            Southampton              56      57.6
6           Norwich City              56      64.9
7       Blackburn Rovers              56      55.6
8        Birmingham City              56      48.7
9   West Bromwich Albion              58      47.6
10     Charlton Athletic              58      63.5
11          Swansea City              59      57.2
12         Oxford United              59      60.1
13          Derby County              59      56.9
14          Bristol City              59      63.3
15     Preston North End              62      71.6
16            Portsmouth              64      55.4
17               Wrexham              65      62.3
18               Watford              65      54.0
19      Sheffield United              66      59.6
20             Hull City              66      80.1
21        Leicester City              68      65.1
22   Queens Park Rangers              73      57.4
23   Sheffield Wednesday              89      91.9

In [42]:
defence_quality_df.to_excel('defence_quality_champ_2526.xlsx', index=False)